Console.Write("Preparar");
Thread.Sleep(500);
Console.Write(" .");
Thread.Sleep(500);
Console.Write(" .");
Thread.Sleep(500);
Console.Write(" .");
Console.ReadKey();
Console.Clear();
Console.Write("Apontar");
Thread.Sleep(500);
Console.Write(" .");
Thread.Sleep(500);
Console.Write(" .");
Thread.Sleep(500);
Console.Write(" .");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Fogo!!!");
Console.ReadKey();
Console.Clear();
